$base = "C:\Users\Derek\proyectos\math_engine"

$files = @(
    "main.py",
    "utils\__init__.py",
    "utils\validaciones.py",
    "utils\input_output.py",
    "utils\graficador.py",
    "utils\logger.py",

    "metodos_numericos\__init__.py",
    "metodos_numericos\raices_ecuaciones\__init__.py",
    "metodos_numericos\raices_ecuaciones\biseccion.py",
    "metodos_numericos\raices_ecuaciones\falsa_posicion.py",
    "metodos_numericos\raices_ecuaciones\secante.py",
    "metodos_numericos\raices_ecuaciones\newton_raphson.py",
    "metodos_numericos\raices_ecuaciones\punto_fijo.py",
    "metodos_numericos\raices_ecuaciones\muller.py",
    "metodos_numericos\raices_ecuaciones\aberth_ehrlich.py",

    "metodos_numericos\interpolacion\__init__.py",
    "metodos_numericos\interpolacion\lagrange.py",
    "metodos_numericos\interpolacion\newton_diferencias_divididas.py",
    "metodos_numericos\interpolacion\spline_lineal.py",
    "metodos_numericos\interpolacion\spline_cubico.py",
    "metodos_numericos\interpolacion\hermite.py",
    "metodos_numericos\interpolacion\racional.py",

    "metodos_numericos\integracion_numerica\__init__.py",
    "metodos_numericos\integracion_numerica\trapecio.py",
    "metodos_numericos\integracion_numerica\simpson_1_3.py",
    "metodos_numericos\integracion_numerica\simpson_3_8.py",
    "metodos_numericos\integracion_numerica\cuadratura_gaussiana.py",
    "metodos_numericos\integracion_numerica\romberg.py",
    "metodos_numericos\integracion_numerica\montecarlo.py",
    "metodos_numericos\integracion_numerica\integral_doble.py",
    "metodos_numericos\integracion_numerica\integral_triple.py",

    "metodos_numericos\ecuaciones_diferenciales\__init__.py",
    "metodos_numericos\ecuaciones_diferenciales\euler.py",
    "metodos_numericos\ecuaciones_diferenciales\euler_mejorado.py",
    "metodos_numericos\ecuaciones_diferenciales\runge_kutta_2.py",
    "metodos_numericos\ecuaciones_diferenciales\runge_kutta_4.py",
    "metodos_numericos\ecuaciones_diferenciales\runge_kutta_fehlberg.py",
    "metodos_numericos\ecuaciones_diferenciales\dormand_prince.py",
    "metodos_numericos\ecuaciones_diferenciales\sistemas_edos.py",
    "metodos_numericos\ecuaciones_diferenciales\edos_orden_superior.py",
    "metodos_numericos\ecuaciones_diferenciales\condiciones_borde.py",
    "metodos_numericos\ecuaciones_diferenciales\pde_parabolicas.py",
    "metodos_numericos\ecuaciones_diferenciales\pde_elipticas.py",

    "algebra_lineal\__init__.py",
    "algebra_lineal\matrices\__init__.py",
    "algebra_lineal\matrices\suma.py",
    "algebra_lineal\matrices\multiplicacion.py",
    "algebra_lineal\matrices\inversa.py",
    "algebra_lineal\matrices\determinante.py",
    "algebra_lineal\matrices\potencia.py",
    "algebra_lineal\matrices\transpuesta.py",
    "algebra_lineal\matrices\rango.py",
    "algebra_lineal\matrices\traza.py",
    "algebra_lineal\matrices\normas.py",
    "algebra_lineal\matrices\factorizacion_lu.py",
    "algebra_lineal\matrices\factorizacion_qr.py",
    "algebra_lineal\matrices\factorizacion_cholesky.py",
    "algebra_lineal\matrices\svd.py",
    "algebra_lineal\matrices\autovalores_potencia.py",
    "algebra_lineal\matrices\autovalores_qr.py",

    "algebra_lineal\sistemas_lineales\__init__.py",
    "algebra_lineal\sistemas_lineales\gauss.py",
    "algebra_lineal\sistemas_lineales\gauss_jordan.py",
    "algebra_lineal\sistemas_lineales\jacobi.py",
    "algebra_lineal\sistemas_lineales\gauss_seidel.py",
    "algebra_lineal\sistemas_lineales\sor.py",
    "algebra_lineal\sistemas_lineales\gradiente_conjugado.py",
    "algebra_lineal\sistemas_lineales\sistemas_tridiagonales.py",

    "calculo\__init__.py",
    "calculo\limites\__init__.py",
    "calculo\limites\limite_numerico.py",
    "calculo\limites\limite_simbolico.py",
    "calculo\limites\limites_laterales.py",
    "calculo\limites\limites_infinitos.py",

    "calculo\derivadas\__init__.py",
    "calculo\derivadas\simbolicas.py",
    "calculo\derivadas\numericas.py",
    "calculo\derivadas\diferencias_finitas.py",
    "calculo\derivadas\derivadas_parciales.py",
    "calculo\derivadas\gradiente.py",
    "calculo\derivadas\jacobiano.py",
    "calculo\derivadas\hessiano.py",

    "calculo\integrales\__init__.py",
    "calculo\integrales\definidas.py",
    "calculo\integrales\indefinidas.py",
    "calculo\integrales\integrales_impropias.py",
    "calculo\integrales\integrales_linea.py",
    "calculo\integrales\integrales_superficie.py",
    "calculo\integrales\integrales_volumen.py",
    "calculo\integrales\series_taylor.py",
    "calculo\integrales\series_fourier.py",
    "calculo\integrales\transformada_fourier.py",
    "calculo\integrales\transformada_laplace.py",

    "probabilidad_estadistica\__init__.py",
    "probabilidad_estadistica\estadistica_descriptiva\__init__.py",
    "probabilidad_estadistica\estadistica_descriptiva\media.py",
    "probabilidad_estadistica\estadistica_descriptiva\mediana.py",
    "probabilidad_estadistica\estadistica_descriptiva\moda.py",
    "probabilidad_estadistica\estadistica_descriptiva\varianza.py",
    "probabilidad_estadistica\estadistica_descriptiva\desviacion_estandar.py",
    "probabilidad_estadistica\estadistica_descriptiva\rango.py",
    "probabilidad_estadistica\estadistica_descriptiva\cuartiles.py",
    "probabilidad_estadistica\estadistica_descriptiva\percentiles.py",
    "probabilidad_estadistica\estadistica_descriptiva\asimetria.py",
    "probabilidad_estadistica\estadistica_descriptiva\curtosis.py",
    "probabilidad_estadistica\estadistica_descriptiva\correlacion.py",
    "probabilidad_estadistica\estadistica_descriptiva\covarianza.py",
    "probabilidad_estadistica\estadistica_descriptiva\histograma.py",
    "probabilidad_estadistica\estadistica_descriptiva\boxplot.py",

    "probabilidad_estadistica\distribuciones\__init__.py",
    "probabilidad_estadistica\distribuciones\normal.py",
    "probabilidad_estadistica\distribuciones\binomial.py",
    "probabilidad_estadistica\distribuciones\poisson.py",
    "probabilidad_estadistica\distribuciones\uniforme.py",
    "probabilidad_estadistica\distribuciones\exponencial.py",
    "probabilidad_estadistica\distribuciones\gamma.py",
    "probabilidad_estadistica\distribuciones\beta.py",
    "probabilidad_estadistica\distribuciones\chi_cuadrado.py",
    "probabilidad_estadistica\distribuciones\t_student.py",
    "probabilidad_estadistica\distribuciones\f_fisher.py",
    "probabilidad_estadistica\distribuciones\lognormal.py",
    "probabilidad_estadistica\distribuciones\weibull.py",
    "probabilidad_estadistica\distribuciones\muestreo_aleatorio.py",

    "probabilidad_estadistica\inferencia\__init__.py",
    "probabilidad_estadistica\inferencia\intervalos_confianza.py",
    "probabilidad_estadistica\inferencia\pruebas_hipotesis.py",
    "probabilidad_estadistica\inferencia\prueba_z.py",
    "probabilidad_estadistica\inferencia\prueba_t.py",
    "probabilidad_estadistica\inferencia\anova.py",
    "probabilidad_estadistica\inferencia\prueba_chi_cuadrado.py",
    "probabilidad_estadistica\inferencia\regresion_lineal.py",
    "probabilidad_estadistica\inferencia\regresion_multiple.py",
    "probabilidad_estadistica\inferencia\bootstrap.py",
    "probabilidad_estadistica\inferencia\bayes.py",
    "probabilidad_estadistica\inferencia\mle.py",

    "optimizacion\__init__.py",
    "optimizacion\optimizacion_1d\__init__.py",
    "optimizacion\optimizacion_1d\busqueda_dorada.py",
    "optimizacion\optimizacion_1d\biseccion_minimos.py",
    "optimizacion\optimizacion_1d\fibonacci.py",
    "optimizacion\optimizacion_1d\interpolacion_cuadratica.py",
    "optimizacion\optimizacion_1d\newton_1d.py",

    "optimizacion\optimizacion_multivariable\__init__.py",
    "optimizacion\optimizacion_multivariable\gradiente_descendente.py",
    "optimizacion\optimizacion_multivariable\newton.py",
    "optimizacion\optimizacion_multivariable\gradiente_conjugado.py",
    "optimizacion\optimizacion_multivariable\bfgs.py",
    "optimizacion\optimizacion_multivariable\lbfgs.py",
    "optimizacion\optimizacion_multivariable\adam.py",
    "optimizacion\optimizacion_multivariable\optimizacion_restricta.py",
    "optimizacion\optimizacion_multivariable\programacion_lineal.py",
    "optimizacion\optimizacion_multivariable\cuadratica_secuencial.py",
    "optimizacion\optimizacion_multivariable\algoritmos_geneticos.py",
    "optimizacion\optimizacion_multivariable\recocido_simulado.py",
    "optimizacion\optimizacion_multivariable\optimizacion_particulas.py",

    "matematicas_discretas\__init__.py",
    "matematicas_discretas\logica\__init__.py",
    "matematicas_discretas\logica\tablas_verdad.py",
    "matematicas_discretas\logica\equivalencias_logicas.py",
    "matematicas_discretas\logica\cuantificadores.py",
    "matematicas_discretas\logica\demostraciones.py",

    "matematicas_discretas\combinatoria\__init__.py",
    "matematicas_discretas\combinatoria\permutaciones.py",
    "matematicas_discretas\combinatoria\combinaciones.py",
    "matematicas_discretas\combinatoria\variaciones.py",
    "matematicas_discretas\combinatoria\coeficientes_binomiales.py",
    "matematicas_discretas\combinatoria\particiones.py",
    "matematicas_discretas\combinatoria\principio_inclusion_exclusion.py",

    "matematicas_discretas\teoria_numeros\__init__.py",
    "matematicas_discretas\teoria_numeros\mcd_mcm.py",
    "matematicas_discretas\teoria_numeros\criba_eratostenes.py",
    "matematicas_discretas\teoria_numeros\factorizacion_primos.py",
    "matematicas_discretas\teoria_numeros\congruencias.py",
    "matematicas_discretas\teoria_numeros\teorema_chino_resto.py",
    "matematicas_discretas\teoria_numeros\phi_euler.py",
    "matematicas_discretas\teoria_numeros\logaritmo_discreto.py",
    "matematicas_discretas\teoria_numeros\rsa.py",

    "teoria_grafos\__init__.py",
    "teoria_grafos\representaciones\__init__.py",
    "teoria_grafos\representaciones\matriz_adyacencia.py",
    "teoria_grafos\representaciones\lista_adyacencia.py",
    "teoria_grafos\representaciones\matriz_incidencia.py",

    "teoria_grafos\recorridos\__init__.py",
    "teoria_grafos\recorridos\bfs.py",
    "teoria_grafos\recorridos\dfs.py",
    "teoria_grafos\recorridos\topological_sort.py",

    "teoria_grafos\caminos_minimos\__init__.py",
    "teoria_grafos\caminos_minimos\dijkstra.py",
    "teoria_grafos\caminos_minimos\bellman_ford.py",
    "teoria_grafos\caminos_minimos\floyd_warshall.py",
    "teoria_grafos\caminos_minimos\a_estrella.py",
    "teoria_grafos\caminos_minimos\johnson.py",

    "teoria_grafos\arboles\__init__.py",
    "teoria_grafos\arboles\prim.py",
    "teoria_grafos\arboles\kruskal.py",
    "teoria_grafos\arboles\boruvka.py",
    "teoria_grafos\arboles\arbol_raiz.py",

    "teoria_grafos\flujos\__init__.py",
    "teoria_grafos\flujos\ford_fulkerson.py",
    "teoria_grafos\flujos\edmonds_karp.py",
    "teoria_grafos\flujos\dinic.py",

    "teoria_grafos\coloracion\__init__.py",
    "teoria_grafos\coloracion\greedy_coloring.py",
    "teoria_grafos\coloracion\welsh_powell.py",

    "analisis_datos\__init__.py",
    "analisis_datos\procesamiento\__init__.py",
    "analisis_datos\procesamiento\limpieza.py",
    "analisis_datos\procesamiento\transformacion.py",
    "analisis_datos\procesamiento\normalizacion.py",
    "analisis_datos\procesamiento\estandarizacion.py",
    "analisis_datos\procesamiento\imputacion.py",
    "analisis_datos\procesamiento\deteccion_outliers.py",
    "analisis_datos\procesamiento\reduccion_dimensionalidad.py",
    "analisis_datos\procesamiento\seleccion_caracteristicas.py",

    "analisis_datos\visualizacion\__init__.py",
    "analisis_datos\visualizacion\graficas_basicas.py",
    "analisis_datos\visualizacion\graficas_avanzadas.py",
    "analisis_datos\visualizacion\mapas_calor.py",
    "analisis_datos\visualizacion\graficos_3d.py",
    "analisis_datos\visualizacion\graficos_interactivos.py",
    "analisis_datos\visualizacion\series_temporales.py",

    "machine_learning\__init__.py",
    "machine_learning\preprocesamiento\__init__.py",
    "machine_learning\preprocesamiento\train_test_split.py",
    "machine_learning\preprocesamiento\cross_validation.py",
    "machine_learning\preprocesamiento\feature_scaling.py",

    "machine_learning\supervisado\__init__.py",
    "machine_learning\supervisado\regresion_lineal.py",
    "machine_learning\supervisado\regresion_polinomial.py",
    "machine_learning\supervisado\regresion_logistica.py",
    "machine_learning\supervisado\knn.py",
    "machine_learning\supervisado\svm.py",
    "machine_learning\supervisado\arboles_decision.py",
    "machine_learning\supervisado\random_forest.py",
    "machine_learning\supervisado\gradient_boosting.py",
    "machine_learning\supervisado\naive_bayes.py",
    "machine_learning\supervisado\redes_neuronales.py",

    "machine_learning\no_supervisado\__init__.py",
    "machine_learning\no_supervisado\kmeans.py",
    "machine_learning\no_supervisado\kmedoids.py",
    "machine_learning\no_supervisado\dbscan.py",
    "machine_learning\no_supervisado\hierarchical_clustering.py",
    "machine_learning\no_supervisado\gaussian_mixture.py",
    "machine_learning\no_supervisado\pca.py",
    "machine_learning\no_supervisado\tsne.py",
    "machine_learning\no_supervisado\autoencoders.py",
    "machine_learning\no_supervisado\reglas_asociacion.py",

    "series_tiempo\__init__.py",
    "series_tiempo\descomposicion.py",
    "series_tiempo\autocorrelacion.py",
    "series_tiempo\arima.py",
    "series_tiempo\sarima.py",
    "series_tiempo\suavizamiento_exponencial.py",
    "series_tiempo\prophet.py",
    "series_tiempo\lstm_temporal.py",

    "procesamiento_senales\__init__.py",
    "procesamiento_senales\convolucion.py",
    "procesamiento_senales\correlacion.py",
    "procesamiento_senales\filtros.py",
    "procesamiento_senales\fft.py",
    "procesamiento_senales\wavelets.py",
    "procesamiento_senales\espectrograma.py",

    "metodos_cientificos\__init__.py",
    "metodos_cientificos\simulacion_montecarlo.py",
    "metodos_cientificos\dinamica_molecular.py",
    "metodos_cientificos\elementos_finitos.py",
    "metodos_cientificos\volumenes_finitos.py",
    "metodos_cientificos\diferencias_finitas_avanzado.py",
    "metodos_cientificos\metodos_malla.py",

    "optimizacion_combinatoria\__init__.py",
    "optimizacion_combinatoria\problema_mochila.py",
    "optimizacion_combinatoria\problema_viajero.py",
    "optimizacion_combinatoria\asignacion_tareas.py",
    "optimizacion_combinatoria\branch_and_bound.py",
    "optimizacion_combinatoria\programacion_dinamica.py",
    "optimizacion_combinatoria\colonia_hormigas.py",
    "optimizacion_combinatoria\enjambre_abejas.py",

    "finanzas_cuantitativas\__init__.py",
    "finanzas_cuantitativas\van_tir.py",
    "finanzas_cuantitativas\amortizacion.py",
    "finanzas_cuantitativas\opciones_financieras.py",
    "finanzas_cuantitativas\var_riesgo.py",
    "finanzas_cuantitativas\simulacion_montecarlo_fin.py",
    "finanzas_cuantitativas\modelos_volatilidad.py",

    "procesamiento_lenguaje_natural\__init__.py",
    "procesamiento_lenguaje_natural\tokenizacion.py",
    "procesamiento_lenguaje_natural\stemming_lemmatization.py",
    "procesamiento_lenguaje_natural\tf_idf.py",
    "procesamiento_lenguaje_natural\word_embeddings.py",
    "procesamiento_lenguaje_natural\analisis_sentimiento.py",
    "procesamiento_lenguaje_natural\clasificacion_texto.py",
    "procesamiento_lenguaje_natural\topic_modeling.py"
)

$created = 0
foreach ($rel in $files) {
    $full = Join-Path $base $rel
    $dir = Split-Path $full -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    if (-not (Test-Path $full)) {
        New-Item -ItemType File -Path $full -Force | Out-Null
        $created++
    }
}

Write-Host "Done. Created $created files."
